apiVersion: v1
kind: Secret
metadata:
  name: microcommunication
type: Opaque
stringData:
  ApiKey: {{ .Values.api.config.apiKey }}
  MongoDbConnectionString: {{ .Values.random.config.database.mongoDbConnectionString }}
  RedisCacheConnectionString: {{ .Values.api.config.signalR.redisCacheConnectionString }}
