apiVersion: v2

name: microcommunication
description: A Helm chart for Kubernetes

appVersion: "1.0"
version: 0.1.0

# dependencies:
#   - name: mongodb
#     version: "16.5.31"
#     repository: "https://charts.bitnami.com/bitnami"
#   - name: redis
#     version: "21.2.12"
#     repository: "https://charts.bitnami.com/bitnami"