ingress:
  enabled: true
  domain: yourdomain.com
  class: istio

api:
  image: robinmanuelthiel/microcommunication-api
  tag: latest
  config:
    apiKey: ""
    signalR:
      redisCacheConnectionString: ""

random:
  image: robinmanuelthiel/microcommunication-random
  tag: latest
  config:
    database:
      mongoDbConnectionString: ""

web:
  image: robinmanuelthiel/microcommunication-web
  tag: latest

# global:
#   security:
#     allowInsecureImages: true

# mongodb:
#  fullnameOverride: mongodb
#  auth:
#   rootPassword: "password"
#  security:
#   allowInsecureImages: true
#  image:
#     registry: docker.io
#     repository: bitnamilegacy/mongodb
#     tag: 8.0.13-debian-12-r0

# redis:
#  fullnameOverride: redis
#  auth:
#   password: "password"
#  security:
#   allowInsecureImages: true
#  architecture: standalone
#  image:
#     registry: docker.io
#     repository: bitnamilegacy/redis
#     tag: 8.2.1-debian-12-r0